-- AlterTable
ALTER TABLE "users" ADD COLUMN "roleId" TEXT NOT NULL DEFAULT '46d36949-70cf-4d0d-9437-5db58336999b';

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "user_roles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
