export type Client = [
  id: string,
  legalName: string,
  tradeName: string,
  type: string,
  protocol: string,
  dataFundation: Date,
  locationAddress: string,
  correspondenceAddress: string,
  nameContact: string,
  numberContact: string,
  hasActivated: number,
  userCreated: number,
  userResponsable: number,
  createdAt: Date,
  updateAt: Date,
]